add transaction
vladibon/wallet-api pull request #3
Opened 2022-04-03 09:20 UTC by mpaukov

Add transaction collection
listTransactions -
GET http://localhost:port/api/transactions
addTransaction -
POST http://localhost:port/api/transactions

2022-04-03 12:40 UTC, vladibon requested changes
Опиши еще, пожалуйста, эти эндпоинты в доках. Файл: api-doc.json

2022-04-03 12:40 UTC, vladibon commented on models/transaction.js
> +// const Joi = require('joi');
Опиши, пожалуйста, валидацию через Joi для транзакции.

2022-04-03 12:40 UTC, vladibon commented on models/transaction.js
> +    typeOfTransaction: {
Вроде, просто `type` достаточно. Зачем такое сложное название?

2022-04-03 12:40 UTC, vladibon commented on controllers/transactions/listTransaction.js
> +  const { page = 1, limit = 20, favorite } = req.query;
Судя по макету, limit = 8 должно быть достаточно для странички пагинации. Когда будет готовый фронт, подкорректируем еще.

2022-04-03 12:40 UTC, vladibon commented on models/transaction.js
> +      required: true,
Там где обязательные поля лучше добавлять текст ошибки: [true, 'Set date for transaction']

2022-04-03 12:40 UTC, vladibon commented on models/transaction.js
> +      required: true,
[true, 'Amount should be at least 0.01']

2022-04-04 08:25 UTC, mpaukov commented on models/transaction.js
> +// const Joi = require('joi');
Сделал

2022-04-04 08:26 UTC, mpaukov commented on models/transaction.js
> +    typeOfTransaction: {
Можно и короткое, делал чтобы было было понятно, что это именно за type

2022-04-04 08:27 UTC, mpaukov commented on controllers/transactions/listTransaction.js
> +  const { page = 1, limit = 20, favorite } = req.query;
Исправил

2022-04-04 08:27 UTC, mpaukov commented on models/transaction.js
> +      required: true,
Исправил

2022-04-04 08:27 UTC, mpaukov commented on models/transaction.js
> +      required: true,
Исправил

2022-04-04 10:06 UTC, vladibon approved these changes
Когда будут готовы эндпоинты по категориям, нужно обязательно будет сделать валидацию поля category на значение одно из существующих. 
Еще доки нужно прописать по категориям.

2022-04-04 10:07 UTC, merged